// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporal/api/compute/v1/scaler.proto

package compute

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ComputeScaler instructs the Temporal Service when to scale up or down the number of
// Workers that comprise a WorkerDeployment.
type ComputeScaler struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The lower limit for the number of Workers (in the WorkerDeployment) to
	// which the ComputeScaler can scale down.
	MinInstances int32 `protobuf:"varint,1,opt,name=min_instances,json=minInstances,proto3" json:"min_instances,omitempty"`
	// The upper limit for the number of Workers (in the WorkerDeployment) to
	// which the ComputeScaler can scale up. Must be greater than or equal to
	// min_instances.
	MaxInstances  int32 `protobuf:"varint,2,opt,name=max_instances,json=maxInstances,proto3" json:"max_instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeScaler) Reset() {
	*x = ComputeScaler{}
	mi := &file_temporal_api_compute_v1_scaler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeScaler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeScaler) ProtoMessage() {}

func (x *ComputeScaler) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_compute_v1_scaler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeScaler.ProtoReflect.Descriptor instead.
func (*ComputeScaler) Descriptor() ([]byte, []int) {
	return file_temporal_api_compute_v1_scaler_proto_rawDescGZIP(), []int{0}
}

func (x *ComputeScaler) GetMinInstances() int32 {
	if x != nil {
		return x.MinInstances
	}
	return 0
}

func (x *ComputeScaler) GetMaxInstances() int32 {
	if x != nil {
		return x.MaxInstances
	}
	return 0
}

var File_temporal_api_compute_v1_scaler_proto protoreflect.FileDescriptor

const file_temporal_api_compute_v1_scaler_proto_rawDesc = "" +
	"\n" +
	"$temporal/api/compute/v1/scaler.proto\x12\x17temporal.api.compute.v1\"Y\n" +
	"\rComputeScaler\x12#\n" +
	"\rmin_instances\x18\x01 \x01(\x05R\fminInstances\x12#\n" +
	"\rmax_instances\x18\x02 \x01(\x05R\fmaxInstancesB\x8d\x01\n" +
	"\x1aio.temporal.api.compute.v1B\vScalerProtoP\x01Z%go.temporal.io/api/compute/v1;compute\xaa\x02\x19Temporalio.Api.Compute.V1\xea\x02\x1cTemporalio::Api::Compute::V1b\x06proto3"

var (
	file_temporal_api_compute_v1_scaler_proto_rawDescOnce sync.Once
	file_temporal_api_compute_v1_scaler_proto_rawDescData []byte
)

func file_temporal_api_compute_v1_scaler_proto_rawDescGZIP() []byte {
	file_temporal_api_compute_v1_scaler_proto_rawDescOnce.Do(func() {
		file_temporal_api_compute_v1_scaler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_api_compute_v1_scaler_proto_rawDesc), len(file_temporal_api_compute_v1_scaler_proto_rawDesc)))
	})
	return file_temporal_api_compute_v1_scaler_proto_rawDescData
}

var file_temporal_api_compute_v1_scaler_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_temporal_api_compute_v1_scaler_proto_goTypes = []any{
	(*ComputeScaler)(nil), // 0: temporal.api.compute.v1.ComputeScaler
}
var file_temporal_api_compute_v1_scaler_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_temporal_api_compute_v1_scaler_proto_init() }
func file_temporal_api_compute_v1_scaler_proto_init() {
	if File_temporal_api_compute_v1_scaler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_api_compute_v1_scaler_proto_rawDesc), len(file_temporal_api_compute_v1_scaler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_api_compute_v1_scaler_proto_goTypes,
		DependencyIndexes: file_temporal_api_compute_v1_scaler_proto_depIdxs,
		MessageInfos:      file_temporal_api_compute_v1_scaler_proto_msgTypes,
	}.Build()
	File_temporal_api_compute_v1_scaler_proto = out.File
	file_temporal_api_compute_v1_scaler_proto_goTypes = nil
	file_temporal_api_compute_v1_scaler_proto_depIdxs = nil
}
