// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporal/api/nexus/v1/events.proto

package nexus

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	v1 "go.temporal.io/api/common/v1"
	v11 "go.temporal.io/api/failure/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OnCompleteHandlerInput is the input data for a Nexus operation's OnComplete handler.
type OnCompleteHandlerInput struct {
	state           protoimpl.MessageState                  `protogen:"open.v1"`
	SourceOperation *OnCompleteHandlerInput_SourceOperation `protobuf:"bytes,1,opt,name=source_operation,json=sourceOperation,proto3" json:"source_operation,omitempty"`
	Outcome         *OnCompleteHandlerInput_Outcome         `protobuf:"bytes,2,opt,name=outcome,proto3" json:"outcome,omitempty"`
	// User-supplied data added to the source invocation. (If applicable.)
	SourceContext *v1.Payload `protobuf:"bytes,3,opt,name=source_context,json=sourceContext,proto3" json:"source_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnCompleteHandlerInput) Reset() {
	*x = OnCompleteHandlerInput{}
	mi := &file_temporal_api_nexus_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnCompleteHandlerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnCompleteHandlerInput) ProtoMessage() {}

func (x *OnCompleteHandlerInput) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_nexus_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnCompleteHandlerInput.ProtoReflect.Descriptor instead.
func (*OnCompleteHandlerInput) Descriptor() ([]byte, []int) {
	return file_temporal_api_nexus_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *OnCompleteHandlerInput) GetSourceOperation() *OnCompleteHandlerInput_SourceOperation {
	if x != nil {
		return x.SourceOperation
	}
	return nil
}

func (x *OnCompleteHandlerInput) GetOutcome() *OnCompleteHandlerInput_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *OnCompleteHandlerInput) GetSourceContext() *v1.Payload {
	if x != nil {
		return x.SourceContext
	}
	return nil
}

// Source operation that was called, and the OnCompleteHandler is responding to.
type OnCompleteHandlerInput_SourceOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Nexus endpoint that was called.
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// The Nexus service that was called.
	Service string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	// The Nexus operation that was called.
	Operation string `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	// The token the operation produced. (If it was an asynchronous Nexus operation.)
	OperationToken string `protobuf:"bytes,4,opt,name=operation_token,json=operationToken,proto3" json:"operation_token,omitempty"`
	// Links that should be used to associate any further operations with the source.
	Links         []*v1.Link `protobuf:"bytes,5,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnCompleteHandlerInput_SourceOperation) Reset() {
	*x = OnCompleteHandlerInput_SourceOperation{}
	mi := &file_temporal_api_nexus_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnCompleteHandlerInput_SourceOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnCompleteHandlerInput_SourceOperation) ProtoMessage() {}

func (x *OnCompleteHandlerInput_SourceOperation) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_nexus_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnCompleteHandlerInput_SourceOperation.ProtoReflect.Descriptor instead.
func (*OnCompleteHandlerInput_SourceOperation) Descriptor() ([]byte, []int) {
	return file_temporal_api_nexus_v1_events_proto_rawDescGZIP(), []int{0, 0}
}

func (x *OnCompleteHandlerInput_SourceOperation) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *OnCompleteHandlerInput_SourceOperation) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *OnCompleteHandlerInput_SourceOperation) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *OnCompleteHandlerInput_SourceOperation) GetOperationToken() string {
	if x != nil {
		return x.OperationToken
	}
	return ""
}

func (x *OnCompleteHandlerInput_SourceOperation) GetLinks() []*v1.Link {
	if x != nil {
		return x.Links
	}
	return nil
}

// The outcome of the source operation.
type OnCompleteHandlerInput_Outcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*OnCompleteHandlerInput_Outcome_Success
	//	*OnCompleteHandlerInput_Outcome_Failure
	Result        isOnCompleteHandlerInput_Outcome_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnCompleteHandlerInput_Outcome) Reset() {
	*x = OnCompleteHandlerInput_Outcome{}
	mi := &file_temporal_api_nexus_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnCompleteHandlerInput_Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnCompleteHandlerInput_Outcome) ProtoMessage() {}

func (x *OnCompleteHandlerInput_Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_nexus_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnCompleteHandlerInput_Outcome.ProtoReflect.Descriptor instead.
func (*OnCompleteHandlerInput_Outcome) Descriptor() ([]byte, []int) {
	return file_temporal_api_nexus_v1_events_proto_rawDescGZIP(), []int{0, 1}
}

func (x *OnCompleteHandlerInput_Outcome) GetResult() isOnCompleteHandlerInput_Outcome_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *OnCompleteHandlerInput_Outcome) GetSuccess() *v1.Payload {
	if x != nil {
		if x, ok := x.Result.(*OnCompleteHandlerInput_Outcome_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *OnCompleteHandlerInput_Outcome) GetFailure() *v11.Failure {
	if x != nil {
		if x, ok := x.Result.(*OnCompleteHandlerInput_Outcome_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isOnCompleteHandlerInput_Outcome_Result interface {
	isOnCompleteHandlerInput_Outcome_Result()
}

type OnCompleteHandlerInput_Outcome_Success struct {
	// The operation was successful, and resulted in the given payload.
	Success *v1.Payload `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type OnCompleteHandlerInput_Outcome_Failure struct {
	// The operation failed. Includes timeout, cancellation, and application errors.
	Failure *v11.Failure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*OnCompleteHandlerInput_Outcome_Success) isOnCompleteHandlerInput_Outcome_Result() {}

func (*OnCompleteHandlerInput_Outcome_Failure) isOnCompleteHandlerInput_Outcome_Result() {}

var File_temporal_api_nexus_v1_events_proto protoreflect.FileDescriptor

const file_temporal_api_nexus_v1_events_proto_rawDesc = "" +
	"\n" +
	"\"temporal/api/nexus/v1/events.proto\x12\x15temporal.api.nexus.v1\x1a$temporal/api/common/v1/message.proto\x1a%temporal/api/failure/v1/message.proto\"\xf1\x04\n" +
	"\x16OnCompleteHandlerInput\x12h\n" +
	"\x10source_operation\x18\x01 \x01(\v2=.temporal.api.nexus.v1.OnCompleteHandlerInput.SourceOperationR\x0fsourceOperation\x12O\n" +
	"\aoutcome\x18\x02 \x01(\v25.temporal.api.nexus.v1.OnCompleteHandlerInput.OutcomeR\aoutcome\x12F\n" +
	"\x0esource_context\x18\x03 \x01(\v2\x1f.temporal.api.common.v1.PayloadR\rsourceContext\x1a\xc2\x01\n" +
	"\x0fSourceOperation\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12'\n" +
	"\x0foperation_token\x18\x04 \x01(\tR\x0eoperationToken\x122\n" +
	"\x05links\x18\x05 \x03(\v2\x1c.temporal.api.common.v1.LinkR\x05links\x1a\x8e\x01\n" +
	"\aOutcome\x12;\n" +
	"\asuccess\x18\x01 \x01(\v2\x1f.temporal.api.common.v1.PayloadH\x00R\asuccess\x12<\n" +
	"\afailure\x18\x02 \x01(\v2 .temporal.api.failure.v1.FailureH\x00R\afailureB\b\n" +
	"\x06resultB\x83\x01\n" +
	"\x18io.temporal.api.nexus.v1B\vEventsProtoP\x01Z!go.temporal.io/api/nexus/v1;nexus\xaa\x02\x17Temporalio.Api.Nexus.V1\xea\x02\x1aTemporalio::Api::Nexus::V1b\x06proto3"

var (
	file_temporal_api_nexus_v1_events_proto_rawDescOnce sync.Once
	file_temporal_api_nexus_v1_events_proto_rawDescData []byte
)

func file_temporal_api_nexus_v1_events_proto_rawDescGZIP() []byte {
	file_temporal_api_nexus_v1_events_proto_rawDescOnce.Do(func() {
		file_temporal_api_nexus_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_api_nexus_v1_events_proto_rawDesc), len(file_temporal_api_nexus_v1_events_proto_rawDesc)))
	})
	return file_temporal_api_nexus_v1_events_proto_rawDescData
}

var file_temporal_api_nexus_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_temporal_api_nexus_v1_events_proto_goTypes = []any{
	(*OnCompleteHandlerInput)(nil),                 // 0: temporal.api.nexus.v1.OnCompleteHandlerInput
	(*OnCompleteHandlerInput_SourceOperation)(nil), // 1: temporal.api.nexus.v1.OnCompleteHandlerInput.SourceOperation
	(*OnCompleteHandlerInput_Outcome)(nil),         // 2: temporal.api.nexus.v1.OnCompleteHandlerInput.Outcome
	(*v1.Payload)(nil),                             // 3: temporal.api.common.v1.Payload
	(*v1.Link)(nil),                                // 4: temporal.api.common.v1.Link
	(*v11.Failure)(nil),                            // 5: temporal.api.failure.v1.Failure
}
var file_temporal_api_nexus_v1_events_proto_depIdxs = []int32{
	1, // 0: temporal.api.nexus.v1.OnCompleteHandlerInput.source_operation:type_name -> temporal.api.nexus.v1.OnCompleteHandlerInput.SourceOperation
	2, // 1: temporal.api.nexus.v1.OnCompleteHandlerInput.outcome:type_name -> temporal.api.nexus.v1.OnCompleteHandlerInput.Outcome
	3, // 2: temporal.api.nexus.v1.OnCompleteHandlerInput.source_context:type_name -> temporal.api.common.v1.Payload
	4, // 3: temporal.api.nexus.v1.OnCompleteHandlerInput.SourceOperation.links:type_name -> temporal.api.common.v1.Link
	3, // 4: temporal.api.nexus.v1.OnCompleteHandlerInput.Outcome.success:type_name -> temporal.api.common.v1.Payload
	5, // 5: temporal.api.nexus.v1.OnCompleteHandlerInput.Outcome.failure:type_name -> temporal.api.failure.v1.Failure
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_temporal_api_nexus_v1_events_proto_init() }
func file_temporal_api_nexus_v1_events_proto_init() {
	if File_temporal_api_nexus_v1_events_proto != nil {
		return
	}
	file_temporal_api_nexus_v1_events_proto_msgTypes[2].OneofWrappers = []any{
		(*OnCompleteHandlerInput_Outcome_Success)(nil),
		(*OnCompleteHandlerInput_Outcome_Failure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_api_nexus_v1_events_proto_rawDesc), len(file_temporal_api_nexus_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_api_nexus_v1_events_proto_goTypes,
		DependencyIndexes: file_temporal_api_nexus_v1_events_proto_depIdxs,
		MessageInfos:      file_temporal_api_nexus_v1_events_proto_msgTypes,
	}.Build()
	File_temporal_api_nexus_v1_events_proto = out.File
	file_temporal_api_nexus_v1_events_proto_goTypes = nil
	file_temporal_api_nexus_v1_events_proto_depIdxs = nil
}
