// Code generated by protoc-gen-go. DO NOT EDIT.
// plugins:
// 	protoc-gen-go
// 	protoc
// source: temporal/api/notificationservice/v1/request_response.proto

package notificationservice

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	v1 "go.temporal.io/api/common/v1"
	v11 "go.temporal.io/api/failure/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OnCompleteRequest is the request type to the NotificationService's OnComplete operation,
// allowing for defining completion handlers for arbitrary operations.
//
// Information about the source operation will be available in the form of a commonpb.Link,
// which will be available separately from this OnCompleteRequest. e.g. a link to the source
// standalone Nexus operation would be found in the nexuspb.StartOperationRequest parameter
// sent to the worker callback. (In addition to this OnCompleteRequest.)
type OnCompleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The result of the source operation.
	//
	// Types that are valid to be assigned to Result:
	//
	//	*OnCompleteRequest_Success
	//	*OnCompleteRequest_Failure
	Result isOnCompleteRequest_Result `protobuf_oneof:"result"`
	// User-supplied data which was added to the source invocation. (As applicable.)
	SourceContext *v1.Payload `protobuf:"bytes,3,opt,name=source_context,json=sourceContext,proto3" json:"source_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnCompleteRequest) Reset() {
	*x = OnCompleteRequest{}
	mi := &file_temporal_api_notificationservice_v1_request_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnCompleteRequest) ProtoMessage() {}

func (x *OnCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_notificationservice_v1_request_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnCompleteRequest.ProtoReflect.Descriptor instead.
func (*OnCompleteRequest) Descriptor() ([]byte, []int) {
	return file_temporal_api_notificationservice_v1_request_response_proto_rawDescGZIP(), []int{0}
}

func (x *OnCompleteRequest) GetResult() isOnCompleteRequest_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *OnCompleteRequest) GetSuccess() *v1.Payload {
	if x != nil {
		if x, ok := x.Result.(*OnCompleteRequest_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *OnCompleteRequest) GetFailure() *v11.Failure {
	if x != nil {
		if x, ok := x.Result.(*OnCompleteRequest_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

func (x *OnCompleteRequest) GetSourceContext() *v1.Payload {
	if x != nil {
		return x.SourceContext
	}
	return nil
}

type isOnCompleteRequest_Result interface {
	isOnCompleteRequest_Result()
}

type OnCompleteRequest_Success struct {
	// The operation was successful, and resulted in the given payload.
	Success *v1.Payload `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type OnCompleteRequest_Failure struct {
	// The operation failed. Includes timeout, cancellation, and application errors.
	Failure *v11.Failure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*OnCompleteRequest_Success) isOnCompleteRequest_Result() {}

func (*OnCompleteRequest_Failure) isOnCompleteRequest_Result() {}

// OnCompleteResponse is the return type of the OnComplete operation.
type OnCompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnCompleteResponse) Reset() {
	*x = OnCompleteResponse{}
	mi := &file_temporal_api_notificationservice_v1_request_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnCompleteResponse) ProtoMessage() {}

func (x *OnCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_notificationservice_v1_request_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnCompleteResponse.ProtoReflect.Descriptor instead.
func (*OnCompleteResponse) Descriptor() ([]byte, []int) {
	return file_temporal_api_notificationservice_v1_request_response_proto_rawDescGZIP(), []int{1}
}

var File_temporal_api_notificationservice_v1_request_response_proto protoreflect.FileDescriptor

const file_temporal_api_notificationservice_v1_request_response_proto_rawDesc = "" +
	"\n" +
	":temporal/api/notificationservice/v1/request_response.proto\x12#temporal.api.notificationservice.v1\x1a$temporal/api/common/v1/message.proto\x1a%temporal/api/failure/v1/message.proto\"\xe0\x01\n" +
	"\x11OnCompleteRequest\x12;\n" +
	"\asuccess\x18\x01 \x01(\v2\x1f.temporal.api.common.v1.PayloadH\x00R\asuccess\x12<\n" +
	"\afailure\x18\x02 \x01(\v2 .temporal.api.failure.v1.FailureH\x00R\afailure\x12F\n" +
	"\x0esource_context\x18\x03 \x01(\v2\x1f.temporal.api.common.v1.PayloadR\rsourceContextB\b\n" +
	"\x06result\"\x14\n" +
	"\x12OnCompleteResponseB\xd2\x01\n" +
	"&io.temporal.api.notificationservice.v1B\x14RequestResponseProtoP\x01Z=go.temporal.io/api/notificationservice/v1;notificationservice\xaa\x02%Temporalio.Api.NotificationService.V1\xea\x02(Temporalio::Api::NotificationService::V1b\x06proto3"

var (
	file_temporal_api_notificationservice_v1_request_response_proto_rawDescOnce sync.Once
	file_temporal_api_notificationservice_v1_request_response_proto_rawDescData []byte
)

func file_temporal_api_notificationservice_v1_request_response_proto_rawDescGZIP() []byte {
	file_temporal_api_notificationservice_v1_request_response_proto_rawDescOnce.Do(func() {
		file_temporal_api_notificationservice_v1_request_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_api_notificationservice_v1_request_response_proto_rawDesc), len(file_temporal_api_notificationservice_v1_request_response_proto_rawDesc)))
	})
	return file_temporal_api_notificationservice_v1_request_response_proto_rawDescData
}

var file_temporal_api_notificationservice_v1_request_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_temporal_api_notificationservice_v1_request_response_proto_goTypes = []any{
	(*OnCompleteRequest)(nil),  // 0: temporal.api.notificationservice.v1.OnCompleteRequest
	(*OnCompleteResponse)(nil), // 1: temporal.api.notificationservice.v1.OnCompleteResponse
	(*v1.Payload)(nil),         // 2: temporal.api.common.v1.Payload
	(*v11.Failure)(nil),        // 3: temporal.api.failure.v1.Failure
}
var file_temporal_api_notificationservice_v1_request_response_proto_depIdxs = []int32{
	2, // 0: temporal.api.notificationservice.v1.OnCompleteRequest.success:type_name -> temporal.api.common.v1.Payload
	3, // 1: temporal.api.notificationservice.v1.OnCompleteRequest.failure:type_name -> temporal.api.failure.v1.Failure
	2, // 2: temporal.api.notificationservice.v1.OnCompleteRequest.source_context:type_name -> temporal.api.common.v1.Payload
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_temporal_api_notificationservice_v1_request_response_proto_init() }
func file_temporal_api_notificationservice_v1_request_response_proto_init() {
	if File_temporal_api_notificationservice_v1_request_response_proto != nil {
		return
	}
	file_temporal_api_notificationservice_v1_request_response_proto_msgTypes[0].OneofWrappers = []any{
		(*OnCompleteRequest_Success)(nil),
		(*OnCompleteRequest_Failure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_api_notificationservice_v1_request_response_proto_rawDesc), len(file_temporal_api_notificationservice_v1_request_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_api_notificationservice_v1_request_response_proto_goTypes,
		DependencyIndexes: file_temporal_api_notificationservice_v1_request_response_proto_depIdxs,
		MessageInfos:      file_temporal_api_notificationservice_v1_request_response_proto_msgTypes,
	}.Build()
	File_temporal_api_notificationservice_v1_request_response_proto = out.File
	file_temporal_api_notificationservice_v1_request_response_proto_goTypes = nil
	file_temporal_api_notificationservice_v1_request_response_proto_depIdxs = nil
}
