// The MIT License
//
// Copyright (c) 2020 Temporal Technologies Inc.  All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: temporal/enums/v1/failed_cause.proto

package enums

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
	strconv "strconv"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DecisionTaskFailedCause int32

const (
	DECISION_TASK_FAILED_CAUSE_UNSPECIFIED                                               DecisionTaskFailedCause = 0
	DECISION_TASK_FAILED_CAUSE_UNHANDLED_DECISION                                        DecisionTaskFailedCause = 1
	DECISION_TASK_FAILED_CAUSE_BAD_SCHEDULE_ACTIVITY_ATTRIBUTES                          DecisionTaskFailedCause = 2
	DECISION_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_ACTIVITY_ATTRIBUTES                    DecisionTaskFailedCause = 3
	DECISION_TASK_FAILED_CAUSE_BAD_START_TIMER_ATTRIBUTES                                DecisionTaskFailedCause = 4
	DECISION_TASK_FAILED_CAUSE_BAD_CANCEL_TIMER_ATTRIBUTES                               DecisionTaskFailedCause = 5
	DECISION_TASK_FAILED_CAUSE_BAD_RECORD_MARKER_ATTRIBUTES                              DecisionTaskFailedCause = 6
	DECISION_TASK_FAILED_CAUSE_BAD_COMPLETE_WORKFLOW_EXECUTION_ATTRIBUTES                DecisionTaskFailedCause = 7
	DECISION_TASK_FAILED_CAUSE_BAD_FAIL_WORKFLOW_EXECUTION_ATTRIBUTES                    DecisionTaskFailedCause = 8
	DECISION_TASK_FAILED_CAUSE_BAD_CANCEL_WORKFLOW_EXECUTION_ATTRIBUTES                  DecisionTaskFailedCause = 9
	DECISION_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_ATTRIBUTES DecisionTaskFailedCause = 10
	DECISION_TASK_FAILED_CAUSE_BAD_CONTINUE_AS_NEW_ATTRIBUTES                            DecisionTaskFailedCause = 11
	DECISION_TASK_FAILED_CAUSE_START_TIMER_DUPLICATE_ID                                  DecisionTaskFailedCause = 12
	DECISION_TASK_FAILED_CAUSE_RESET_STICKY_TASK_QUEUE                                   DecisionTaskFailedCause = 13
	DECISION_TASK_FAILED_CAUSE_WORKFLOW_WORKER_UNHANDLED_FAILURE                         DecisionTaskFailedCause = 14
	DECISION_TASK_FAILED_CAUSE_BAD_SIGNAL_WORKFLOW_EXECUTION_ATTRIBUTES                  DecisionTaskFailedCause = 15
	DECISION_TASK_FAILED_CAUSE_BAD_START_CHILD_EXECUTION_ATTRIBUTES                      DecisionTaskFailedCause = 16
	DECISION_TASK_FAILED_CAUSE_FORCE_CLOSE_DECISION                                      DecisionTaskFailedCause = 17
	DECISION_TASK_FAILED_CAUSE_FAILOVER_CLOSE_DECISION                                   DecisionTaskFailedCause = 18
	DECISION_TASK_FAILED_CAUSE_BAD_SIGNAL_INPUT_SIZE                                     DecisionTaskFailedCause = 19
	DECISION_TASK_FAILED_CAUSE_RESET_WORKFLOW                                            DecisionTaskFailedCause = 20
	DECISION_TASK_FAILED_CAUSE_BAD_BINARY                                                DecisionTaskFailedCause = 21
	DECISION_TASK_FAILED_CAUSE_SCHEDULE_ACTIVITY_DUPLICATE_ID                            DecisionTaskFailedCause = 22
	DECISION_TASK_FAILED_CAUSE_BAD_SEARCH_ATTRIBUTES                                     DecisionTaskFailedCause = 23
)

var DecisionTaskFailedCause_name = map[int32]string{
	0:  "Unspecified",
	1:  "UnhandledDecision",
	2:  "BadScheduleActivityAttributes",
	3:  "BadRequestCancelActivityAttributes",
	4:  "BadStartTimerAttributes",
	5:  "BadCancelTimerAttributes",
	6:  "BadRecordMarkerAttributes",
	7:  "BadCompleteWorkflowExecutionAttributes",
	8:  "BadFailWorkflowExecutionAttributes",
	9:  "BadCancelWorkflowExecutionAttributes",
	10: "BadRequestCancelExternalWorkflowExecutionAttributes",
	11: "BadContinueAsNewAttributes",
	12: "StartTimerDuplicateId",
	13: "ResetStickyTaskQueue",
	14: "WorkflowWorkerUnhandledFailure",
	15: "BadSignalWorkflowExecutionAttributes",
	16: "BadStartChildExecutionAttributes",
	17: "ForceCloseDecision",
	18: "FailoverCloseDecision",
	19: "BadSignalInputSize",
	20: "ResetWorkflow",
	21: "BadBinary",
	22: "ScheduleActivityDuplicateId",
	23: "BadSearchAttributes",
}

var DecisionTaskFailedCause_value = map[string]int32{
	"Unspecified":                                         0,
	"UnhandledDecision":                                   1,
	"BadScheduleActivityAttributes":                       2,
	"BadRequestCancelActivityAttributes":                  3,
	"BadStartTimerAttributes":                             4,
	"BadCancelTimerAttributes":                            5,
	"BadRecordMarkerAttributes":                           6,
	"BadCompleteWorkflowExecutionAttributes":              7,
	"BadFailWorkflowExecutionAttributes":                  8,
	"BadCancelWorkflowExecutionAttributes":                9,
	"BadRequestCancelExternalWorkflowExecutionAttributes": 10,
	"BadContinueAsNewAttributes":                          11,
	"StartTimerDuplicateId":                               12,
	"ResetStickyTaskQueue":                                13,
	"WorkflowWorkerUnhandledFailure":                      14,
	"BadSignalWorkflowExecutionAttributes":                15,
	"BadStartChildExecutionAttributes":                    16,
	"ForceCloseDecision":                                  17,
	"FailoverCloseDecision":                               18,
	"BadSignalInputSize":                                  19,
	"ResetWorkflow":                                       20,
	"BadBinary":                                           21,
	"ScheduleActivityDuplicateId":                         22,
	"BadSearchAttributes":                                 23,
}

func (DecisionTaskFailedCause) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6aa03c6c7587cda2, []int{0}
}

type StartChildWorkflowExecutionFailedCause int32

const (
	START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED             StartChildWorkflowExecutionFailedCause = 0
	START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_WORKFLOW_ALREADY_EXISTS StartChildWorkflowExecutionFailedCause = 1
)

var StartChildWorkflowExecutionFailedCause_name = map[int32]string{
	0: "Unspecified",
	1: "WorkflowAlreadyExists",
}

var StartChildWorkflowExecutionFailedCause_value = map[string]int32{
	"Unspecified":           0,
	"WorkflowAlreadyExists": 1,
}

func (StartChildWorkflowExecutionFailedCause) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6aa03c6c7587cda2, []int{1}
}

type CancelExternalWorkflowExecutionFailedCause int32

const (
	CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED                           CancelExternalWorkflowExecutionFailedCause = 0
	CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND CancelExternalWorkflowExecutionFailedCause = 1
)

var CancelExternalWorkflowExecutionFailedCause_name = map[int32]string{
	0: "Unspecified",
	1: "ExternalWorkflowExecutionNotFound",
}

var CancelExternalWorkflowExecutionFailedCause_value = map[string]int32{
	"Unspecified":                       0,
	"ExternalWorkflowExecutionNotFound": 1,
}

func (CancelExternalWorkflowExecutionFailedCause) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6aa03c6c7587cda2, []int{2}
}

type SignalExternalWorkflowExecutionFailedCause int32

const (
	SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED                           SignalExternalWorkflowExecutionFailedCause = 0
	SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND SignalExternalWorkflowExecutionFailedCause = 1
)

var SignalExternalWorkflowExecutionFailedCause_name = map[int32]string{
	0: "Unspecified",
	1: "ExternalWorkflowExecutionNotFound",
}

var SignalExternalWorkflowExecutionFailedCause_value = map[string]int32{
	"Unspecified":                       0,
	"ExternalWorkflowExecutionNotFound": 1,
}

func (SignalExternalWorkflowExecutionFailedCause) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6aa03c6c7587cda2, []int{3}
}

func init() {
	proto.RegisterEnum("temporal.enums.v1.DecisionTaskFailedCause", DecisionTaskFailedCause_name, DecisionTaskFailedCause_value)
	proto.RegisterEnum("temporal.enums.v1.StartChildWorkflowExecutionFailedCause", StartChildWorkflowExecutionFailedCause_name, StartChildWorkflowExecutionFailedCause_value)
	proto.RegisterEnum("temporal.enums.v1.CancelExternalWorkflowExecutionFailedCause", CancelExternalWorkflowExecutionFailedCause_name, CancelExternalWorkflowExecutionFailedCause_value)
	proto.RegisterEnum("temporal.enums.v1.SignalExternalWorkflowExecutionFailedCause", SignalExternalWorkflowExecutionFailedCause_name, SignalExternalWorkflowExecutionFailedCause_value)
}

func init() {
	proto.RegisterFile("temporal/enums/v1/failed_cause.proto", fileDescriptor_6aa03c6c7587cda2)
}

var fileDescriptor_6aa03c6c7587cda2 = []byte{
	// 731 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcd, 0x52, 0xdb, 0x48,
	0x10, 0xb6, 0xf6, 0x87, 0xdd, 0x1d, 0xf6, 0x47, 0xcc, 0xb2, 0xcb, 0x4d, 0xa7, 0x5d, 0xaa, 0x70,
	0x2d, 0xf6, 0xb2, 0xec, 0x42, 0xb1, 0x4e, 0x8a, 0x8c, 0x47, 0x6d, 0x3c, 0x65, 0x21, 0x99, 0x99,
	0x11, 0xb6, 0xb9, 0x4c, 0x29, 0x46, 0x10, 0x15, 0xc6, 0xa2, 0x6c, 0x43, 0x38, 0xe6, 0x01, 0x72,
	0xc8, 0x63, 0xe4, 0x94, 0xe7, 0xe0, 0xc8, 0x91, 0xaa, 0x5c, 0x82, 0xb9, 0xe4, 0xc8, 0x23, 0xa4,
	0xe4, 0x60, 0x22, 0x02, 0x25, 0xc9, 0xb9, 0xcd, 0x4f, 0x7f, 0xdf, 0xf4, 0xd7, 0xdd, 0xd3, 0xd5,
	0xe8, 0x8f, 0x81, 0x7f, 0x78, 0x14, 0xf6, 0xbc, 0x4e, 0xd1, 0xef, 0x1e, 0x1f, 0xf6, 0x8b, 0x27,
	0x4b, 0xc5, 0x3d, 0x2f, 0xe8, 0xf8, 0xbb, 0xaa, 0xed, 0x1d, 0xf7, 0xfd, 0xc2, 0x51, 0x2f, 0x1c,
	0x84, 0x78, 0x66, 0x6c, 0x55, 0x18, 0x59, 0x15, 0x4e, 0x96, 0xf2, 0x6f, 0xa7, 0xd1, 0x9c, 0xe9,
	0xb7, 0x83, 0x7e, 0x10, 0x76, 0xa5, 0xd7, 0x3f, 0xa8, 0x8c, 0x50, 0x34, 0x02, 0xe1, 0x3c, 0x9a,
	0x37, 0x81, 0x32, 0xc1, 0x1c, 0x5b, 0x49, 0x22, 0x6a, 0xaa, 0x42, 0x98, 0x05, 0xa6, 0xa2, 0xc4,
	0x15, 0xa0, 0x5c, 0x5b, 0xd4, 0x81, 0xb2, 0x0a, 0x03, 0x53, 0xcf, 0xe1, 0x25, 0xb4, 0x98, 0x68,
	0x5b, 0x25, 0xb6, 0x19, 0xed, 0xc7, 0x46, 0xba, 0x86, 0xd7, 0x51, 0x29, 0x01, 0x52, 0x26, 0xa6,
	0x12, 0xb4, 0x0a, 0xa6, 0x6b, 0x81, 0x22, 0x54, 0xb2, 0x6d, 0x26, 0x5b, 0x8a, 0x48, 0xc9, 0x59,
	0xd9, 0x95, 0x20, 0xf4, 0xaf, 0x30, 0x20, 0x92, 0x42, 0xc0, 0x61, 0xcb, 0x05, 0x21, 0x15, 0x25,
	0x36, 0x05, 0xeb, 0x41, 0x9a, 0xaf, 0xf1, 0x1a, 0xfa, 0x2f, 0xcd, 0x0f, 0x49, 0xb8, 0x54, 0x92,
	0x6d, 0x02, 0x8f, 0x43, 0xbf, 0xc1, 0xff, 0xa3, 0x95, 0x14, 0xe8, 0xcd, 0xcb, 0xf7, 0xb0, 0xdf,
	0xe2, 0x12, 0x5a, 0x4d, 0xf5, 0x9e, 0x3a, 0xdc, 0x54, 0x9b, 0x84, 0xd7, 0xee, 0x82, 0xa7, 0x30,
	0x43, 0x90, 0xf6, 0xb0, 0xb3, 0x59, 0xb7, 0x40, 0x82, 0x6a, 0x38, 0xbc, 0x56, 0xb1, 0x9c, 0x86,
	0x82, 0x26, 0x50, 0x57, 0x46, 0x88, 0x18, 0xd5, 0x77, 0x19, 0xa2, 0x18, 0x1d, 0xa4, 0xd0, 0x7c,
	0x8f, 0x37, 0x10, 0xcd, 0x16, 0x8a, 0x64, 0xa2, 0x1f, 0x70, 0x13, 0xc9, 0xc9, 0xb2, 0x0a, 0x4d,
	0x09, 0xdc, 0x26, 0x69, 0xcc, 0x08, 0x3f, 0x46, 0x6b, 0xa9, 0x41, 0xb3, 0x25, 0xb3, 0x5d, 0x50,
	0x44, 0x28, 0x1b, 0x1a, 0x71, 0xf8, 0x34, 0x5e, 0x45, 0xcb, 0x09, 0xf0, 0x78, 0x8d, 0x98, 0x6e,
	0xdd, 0x62, 0x94, 0x48, 0x50, 0xcc, 0xd4, 0x7f, 0xc4, 0x2b, 0xe8, 0x9f, 0x04, 0x20, 0x07, 0x01,
	0x52, 0x09, 0xc9, 0x68, 0xad, 0xf5, 0xf1, 0x7a, 0xcb, 0x05, 0x17, 0xf4, 0x9f, 0xf0, 0x13, 0xf4,
	0x28, 0x01, 0x77, 0xab, 0x36, 0x5a, 0x00, 0x8f, 0xfd, 0xb1, 0xc8, 0xcc, 0xe5, 0xa0, 0xff, 0x9c,
	0x21, 0x29, 0x82, 0x6d, 0xa4, 0x87, 0xee, 0x17, 0x4c, 0xd1, 0x7a, 0xa6, 0x3f, 0x42, 0xab, 0xcc,
	0x32, 0x1f, 0x26, 0xd1, 0xf1, 0x32, 0x2a, 0x26, 0x90, 0x54, 0x1c, 0x4e, 0x41, 0x51, 0xcb, 0x11,
	0xf0, 0xa9, 0x4b, 0xcc, 0xa4, 0x04, 0x2f, 0xda, 0x38, 0xdb, 0xc0, 0x3f, 0xc7, 0x61, 0xfc, 0x2f,
	0xfa, 0x3b, 0x9b, 0x74, 0x66, 0xd7, 0x5d, 0xa9, 0x04, 0xdb, 0x01, 0xfd, 0x57, 0xbc, 0x88, 0x16,
	0x52, 0x53, 0x35, 0x8e, 0x95, 0x3e, 0x8b, 0x17, 0xd0, 0x9f, 0x29, 0x8f, 0x94, 0x99, 0x4d, 0x78,
	0x4b, 0xff, 0x2d, 0xa5, 0xf8, 0xee, 0x77, 0xba, 0x3b, 0x35, 0xf4, 0x7b, 0x16, 0x39, 0x40, 0x38,
	0xad, 0xc6, 0x23, 0x3e, 0x97, 0x7f, 0xa3, 0xa1, 0x79, 0x31, 0xf0, 0x7a, 0x03, 0xfa, 0x2c, 0xe8,
	0xec, 0x36, 0xc2, 0xde, 0xc1, 0x5e, 0x27, 0x7c, 0x0e, 0xa7, 0x7e, 0xfb, 0x78, 0x10, 0x84, 0xdd,
	0x78, 0xb3, 0x2f, 0xa1, 0xd5, 0x78, 0x0a, 0x1f, 0x28, 0x88, 0x84, 0xee, 0xbf, 0x81, 0xe8, 0x24,
	0xe0, 0xdb, 0x7b, 0x62, 0x71, 0x20, 0x66, 0x4b, 0x41, 0x93, 0x09, 0x29, 0x74, 0x2d, 0x7f, 0xa6,
	0xa1, 0x3c, 0xf5, 0xba, 0x6d, 0xbf, 0x03, 0xa7, 0x03, 0xbf, 0xd7, 0xf5, 0x3a, 0x89, 0x4e, 0xaf,
	0xa3, 0x52, 0x86, 0x26, 0x90, 0xe0, 0x78, 0x0b, 0xb9, 0x93, 0x12, 0x24, 0x19, 0xda, 0x8e, 0x54,
	0x15, 0xc7, 0xb5, 0xcd, 0x1b, 0x29, 0x22, 0xd8, 0xef, 0x7a, 0x99, 0xa5, 0xdc, 0x14, 0xe4, 0x97,
	0x4b, 0x99, 0x94, 0x20, 0xa3, 0x94, 0xf2, 0x4b, 0xed, 0xfc, 0xd2, 0xc8, 0x5d, 0x5c, 0x1a, 0xb9,
	0xeb, 0x4b, 0x43, 0x7b, 0x31, 0x34, 0xb4, 0xd7, 0x43, 0x43, 0x3b, 0x1b, 0x1a, 0xda, 0xf9, 0xd0,
	0xd0, 0xde, 0x0d, 0x0d, 0xed, 0xfd, 0xd0, 0xc8, 0x5d, 0x0f, 0x0d, 0xed, 0xd5, 0x95, 0x91, 0x3b,
	0xbf, 0x32, 0x72, 0x17, 0x57, 0x46, 0x0e, 0xcd, 0x06, 0x61, 0xe1, 0xde, 0xc4, 0x51, 0xd6, 0x63,
	0xaa, 0xeb, 0xd1, 0x58, 0x52, 0xd7, 0x76, 0xfe, 0xda, 0x8f, 0x59, 0x06, 0x61, 0x71, 0xbc, 0x5e,
	0x1c, 0xcd, 0x2d, 0xb7, 0x33, 0x4d, 0x69, 0xb4, 0x78, 0x3a, 0x35, 0x3a, 0x5d, 0xfe, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xec, 0x78, 0x13, 0xa8, 0xf5, 0x08, 0x00, 0x00,
}

func (x DecisionTaskFailedCause) String() string {
	s, ok := DecisionTaskFailedCause_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x StartChildWorkflowExecutionFailedCause) String() string {
	s, ok := StartChildWorkflowExecutionFailedCause_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x CancelExternalWorkflowExecutionFailedCause) String() string {
	s, ok := CancelExternalWorkflowExecutionFailedCause_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x SignalExternalWorkflowExecutionFailedCause) String() string {
	s, ok := SignalExternalWorkflowExecutionFailedCause_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
